### ISSUE TITLE
2D team split behavior when xrange > npes

### ISSUE THREAD

**Issue by davidozog** [openshmem-org/specification#326] opened 2020-01-07 16:22 UTC
@jdinan and I ran into a minor implementation problem when testing a 2D team split with `xrange > npes` here:
https://github.com/davidozog/sandia-shmem/pull/9

Perhaps I'm missing something in my interpretation of the API description, but I'm not sure it's explicit about this case.  Do we create an "unfilled" xteam (similar to the unfilled yteams when `npes(parent_team) % xrange > 0`), or should we require that `xrange` be less than or equal to the number of PEs in the parent team?

For what it's worth, I think it's a bit more self-consistent to create the unfilled xteam; but it's also simpler to just require `xrange <= npes`.  Any thoughts?

**Comment by naveen-rn** [comment] 2020-01-07 16:57
duplicate of https://github.com/gmegan/specification/issues/122

**Comment by jdinan** [comment] 2020-01-07 19:30
@naveen-rn Thanks for the reference. Now that teams is merged, I suggest that we move issues to the openshmem-org repository, so that we can better track them relative to the OpenSHMEM 1.5 release.

**Comment by nspark** [comment] 2020-01-10 21:23
I'm happy to work with @davidozog on suggesting a clarifying note to the Teams section committee.

**Closed** 2020-03-04 15:26 UTC
Labels: SectionCommittee
