### ISSUE TITLE
Signed bitwise AMO support

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#80] opened 2017-06-14 19:34 UTC
Is there a reason why bitwise atomic operations include two (2) signed types (`int32` and `int64`) out of the seven (7) types? 
```
uint
ulong
ulonglong
int32
int64
uint32
uint64
```
This seems inconsistent.  I'm not sure what it means to have a bitwise operation on signed data.
Also, it probably doesn't make sense to add `size`, despite being unsigned.  If others concur, I will submit the pull request to remove `int32` and `int64`.

For reference:
https://github.com/openshmem-org/specification/blob/osh_spec_next/content/atomics_intro.tex

**Comment by jdinan** [comment] 2017-06-14 20:12
The representation for ```int``` and ```long``` types is not defined by the C language, so bitwise arithmetic on variables with these types may not be portable.  Might have been a good idea to include a rationale for this choice in the spec..

**Comment by jamesaross** [comment] 2017-06-14 20:17
I don't think portability was the reason for excluding `int` and `long`. By that logic, `unsigned int` (`uint`) and `unsigned long` (`ulong`) shouldn't be included in the bitwise AMO list because they are the same undefined size as `int` and `long`.

**Comment by jdinan** [comment] 2017-06-14 20:20
The size isn't an issue.  The problem is that C doesn't specify how the bits are used: whether the representation is two's complement, one's complement, or sign and magnitude.

**Comment by jeffhammond** [comment] 2017-06-14 20:30
@jamesaross Are you arguing against this for the reasons listed in https://www.securecoding.cert.org/confluence/display/c/INT13-C.+Use+bitwise+operators+only+on+unsigned+operands?  I think OpenSHMEM programmers know what system they are using and what the integer representation is, and thus can use bitwise operations on signed integers safely.

**Comment by jamesaross** [comment] 2017-06-14 20:41
@jeffhammond, not really.  The selection of the seven types seemed inconsistent to me, but @jdinan's explanation makes sense.  The rationale isn't immediately obvious.

**Comment by nspark** [comment] 2017-07-26 20:05
@jamesaross Are you comfortable adding a label of "invalid" and closing this issue?

**Closed** 2017-07-26 21:06 UTC
