### ISSUE TITLE
Purge/Fix Appendix D

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#191] opened 2017-12-15 00:05 UTC
## Proposed Change

Either fix or remove Appendix D from specification document.  It adds nothing (well, perhaps confusion) to the specification and is slowly going out-of-date.

## Context

As noted by @jeffhammond:

Appendix D references SGI, which is renamed to HPE elsewhere.  Obviously, this is of no practical consequence, but I guess it should be fixed in the next version.

I'm also not clear what purpose Appendix D actually serves.  I'd much rather see us define something useful, such as preprocessor symbols the implementation can define to indicate whether or not SHMEM PEs are equivalent to MPI processes (i.e. ranks in MPI_COMM_WORLD), UPC threads, or any other unit of parallel execution that we think matters.

Finally, I'd like to see "the MPI rank within the MPI_COMM_WORLD environment variable" stricken or corrected, because that phrase makes no sense.

**Comment by minsii** [comment] 2018-07-23 19:18
As discussed with @manjugv @davidozog @nspark during the spec meeting, we think it is still useful to have the interoperability description for portable OpenSHMEM + MPI programming. We agreed that the current section is outdated and contains inaccurate description. However, we could improve (or entirely rewrite) it instead of removing.

I propose that we could consider the following topics:
(1) Standardization of a minimal set of requirements for OpenSHMEM + MPI programs (e.g., init/finalize, perhaps MPI rank <-> SHMEM PE).
(2) Clarification of any undefined behavior caused by mixed use of these programming models (e.g., atomicity, ordering).
(3) Advice to users/implementors for implementation-specific features. 

Please let me know if you have any feedback or suggestion on this. I can summarize an initial draft  and bring it into a working group for future discussion.

**Comment by jdinan** [comment] 2018-07-26 15:09
An annex that captures a set of requirements for an MPI library to claim SHMEM interoperability and vice versa would be useful.  We have an intern who has been working on MPI interoperability with SOS and can share what we've learned (e.g. PMI is a pain).  Depending on how detailed you want to get, this could become a fairly substantial undertaking (e.g. MPI dynamic processes, interaction if any between MPI operations and shmem_wait, ...).

Should we hang on to the proposal to remove Annex D in case the replacement is not ready in time for the next release?

**Comment by minsii** [comment] 2018-07-27 22:06
Agreed. Removing Annex D could be a temporary fix in the next release in case we cannot finish the interoperability section in time. 

This section might need touch several runtime implementations of MPI+OpenSHMEM combination: (1) standalone OpenSHMEM such as SOS, (2) runtime supports both MPI and OpenSHMEM such as OpenMPI (and MVAPICH?), and (3) OpenSHMEM on top of MPI such as OSHMPI. We may want to summarize the common semantics for all the three types.

**Comment by minsii** [comment] 2018-08-01 14:19
@jdinan Could you please provide a few more information about the PMI issue you mentioned ? We are currently discussing some design change of MPICH hydra. It might be great if we could consider SHMEM interoperability.

**Comment by manjugv** [comment] 2018-08-01 14:38
@jdinan I would be interested to hear as well. We have some effort here at ORNL, where we are thinking about interoperability between various programming models (MPI, OpenMP, OpenSHMEM) from PMI perspective. So this discussion in general could be useful.

**Comment by jdinan** [comment] 2018-08-01 21:16
One of the issues with PMI-1 and PMI-2 (PMIx should hopefully fix some of these issues, but I haven't looked into it yet) has to do with initializing and finalizing the PMI client library.  The PMI API doesn't support multiple sessions, so you have to do the usual `PMI_Initialized` check.  There is also no `PMI_Finalized` check, so you cross your fingers and hope that works (assuming you initialized PMI).  Our experiences have shown that PMI servers don't like to talk to multiple PMI clients and we have generally had more success sharing the client library than using separate client libraries and sharing the server (although, this is not always easy to do, since PMI is not always built as a separate library).  When multiple runtimes share PMI, they also share the same KVS, so you end up needing to prepend a "namespace" string to key names (e.g. we prepend something like "shmem-pe_id-") to avoid collisions.

You can make it work, but it ends up being a bit fragile.  For instance, if the user finalizes MPI/SHMEM in the reverse order in which they were initialized, it will probably break.  We have also found that some MPI implementations don't expect another library to be using PMI, so they don't check `PMI_Initialized`.  It generally works better for users to do `MPI_Init(...); shmem_init(); ... shmem_finalize(); MPI_Finalize();`.  We have a patch in the works to just use MPI to bootstrap SOS and avoid using PMI entirely.

**Comment by tonycurtis** [comment] 2018-08-01 21:41
> On Aug 1, 2018, at 5:16 PM, James Dinan <notifications@github.com> wrote:
> 
> One of the issues with PMI-1 and PMI-2 (PMIx should hopefully fix some of these issues, but I haven't looked into it yet) has to do with initializing and finalizing the PMI client library.
> 

I’m using PMIx for the OSSS reference implementation.  I could ask Ralph Castain if he or someone else could give us a tutorial or intro presentation if anyone is interested.

tony

**Comment by jdinan** [comment] 2018-08-02 13:57
We're planning to chat with Ralph later this week about PMIx.  I can let you know what we learn.  The other changes I mentioned should be merged into SOS within the next week or so.

**Comment by jdinan** [comment] 2018-08-07 15:56
PMIx should fix the init/finalize issues I mentioned earlier.  The KVS is still shared, but this is easy to work around.  Ralph suggested some neat things you can do to share information between MPI and SHMEM that will be fun to look into.

**Comment by jdinan** [comment] 2018-08-07 15:57
Coming back to earlier discussion, @minsii how would you like to handle PR #215 which is ready for a vote at the upcoming meeting?

**Comment by minsii** [comment] 2018-08-07 16:01
It is good to know PMIx fixes it and our team will be interested in the MPI/SHMEM interoperability in MPICH hydra. 

About PR #215, I think we can go ahead and remove it in this release. The new interoperability section will need more time to prepare.

**Comment by RaymondMichael** [comment] 2018-08-07 17:32
Also, a MPI_Init_thread(MPI_THREAD_SINGLE,) followed by a shmem_init_thread(SHMEM_THREAD_MULTIPLE) will only get you SHMEM_THREAD_SINGLE. SHMEM_THREAD_SINGLE followed by MPI_THREAD_MULTIPLE will get you MPI_THREAD_SINGLE.

**Comment by jeffhammond** [comment] 2018-08-07 18:04
So here's an idea:
```
int shmem_query_interoperability(int property);
```

Standardizes interoperability properties could include:

Property|Meaning
---|---
``UPC_THREADS_ARE_PES``|True if UPC threads and SHMEM PEs are equivalent.
``FORTRAN_IMAGES_ARE_PES``|True if Fortran coarray images and SHMEM PEs are equivalent.
``MPI_PROCESSES_ARE_PES``|True if MPI processes i.e. ranks in `MPI_COMM_WORLD` and SHMEM PEs are equivalent, assuming no use of MPI dynamic process management or MPMD launching.
``SHMEM_INITIALIZES_MPI``|True if `shmem_init(_thread)` includes an equivalent call to `MPI_Init(_thread)`
``MPI_INITIALIZES_SHMEM``|True if `MPI_Init(_thread)` includes an equivalent call to `shmem_init(_thread)`.

Implementations would be free to add additional properties to meet user needs.

**Comment by minsii** [comment] 2018-08-07 18:30
@RaymondMichael @jeffhammond : Thanks a lot for your inputs. I am summarizing the status/ideas into today's slide.

**Comment by minsii** [comment] 2018-08-07 21:10
Here is the slides used at today's thread WG call.
[SHMEM_Interoperability_20180807.pptx](https://github.com/openshmem-org/specification/files/2268059/SHMEM_Interoperability_20180807.pptx)

I will put all slides also at: https://anl.box.com/s/nrlvayblczmlvhnjsoxulw4czopbadz0

**Comment by khamidouche** [comment] 2018-08-13 14:59
MVAPICH2-X is also something similar to HPE. It uses UCR as a low-level runtime (similar to UCX). So calling MPI_init or OpenSHMEM_init it will end up by initializing the UCR runtime.  So in MV2-X all the Properties in @jeffhammond's table are true. 
Technically all the runtimes that rely on the low-level runtimes like UCX/libfabric should provide interoperability as it is the main goal of these runtimes.

**Comment by khamidouche** [comment] 2018-08-13 18:46
@minsii I'm sorry, but as I'm not anymore part of the MVAPICH team, I am not sure I can talk about the implementation details especially as the code is closed. We might need to check with OSU folks for this.

**Comment by minsii** [comment] 2018-08-22 15:16
Here is the slides for the discussion at Threads Working Group on August 22, 2018.
[SHMEM_Interoperability_20180822.pptx](https://github.com/openshmem-org/specification/files/2310945/SHMEM_Interoperability_20180822.pptx)

**Closed** 2018-08-23 13:53 UTC
