### ISSUE TITLE
Puts from PE0 to PE1 in figures/quiet.pdf are mislabeled

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#88] opened 2017-07-23 03:02 UTC
[figures/quiet.pdf](https://github.com/openshmem-org/specification/blob/96003a7025a90058c172d27f81cada785bc74076/figures/quiet.pdf) has puts from PE0 to PE1 mislabeled with destination "PE 0" instead of correct "PE 1". I don't have OmniGraffle to fix source file [figures/quiet.graffle](https://github.com/openshmem-org/specification/blob/96003a7025a90058c172d27f81cada785bc74076/figures/quiet.graffle).

This image appears in "Synchronization and Communication Ordering in OpenSHMEM".

**Comment by nspark** [comment] 2017-07-24 14:16
Aside: If we create new graphics in the future for the specification, can we create them as SVGs? Using an open format with plenty of good FOSS editors (especially Inkscape) is my preference.

Note: I'm not suggesting we go off and convert all the source images to SVG.

**Comment by shamisp** [comment] 2017-07-24 14:31
@BryantLam you can blame me :) I will work to fix it.
@nspark AFAIK you can use inkscape to open OmniGraffle files.

**Comment by swpoole** [comment] 2017-07-25 11:59
If no one has OmniGraggle, please let me know and I will fix the image.

**Comment by jamesaross** [comment] 2017-07-25 14:37
For this issue, it seems like one should be able to directly modify the source without the need for special software:
[figures/quiet.graffle#L1105](https://github.com/openshmem-org/specification/blob/96003a7025a90058c172d27f81cada785bc74076/figures/quiet.graffle#L1105) "PE 1" -> "PE 0"
[figures/quiet.graffle#L1129](https://github.com/openshmem-org/specification/blob/96003a7025a90058c172d27f81cada785bc74076/figures/quiet.graffle#L1129) "PE 0" -> "PE 1"

**Comment by shamisp** [comment] 2017-07-25 15:39
inkscape opens and edits graffle format. No special software required.

**Comment by swpoole** [comment] 2017-07-25 23:18
Why couldn't we just use the existing macro for "deprecation". It is in RED and can just be put in front of all of the FORTRAN API defs?
I have OmniGraffle on the Mac. I went in and changed the shmem_quiet image.
In the V1.4 text, there also seems to be a bug introduced in that you do not get the macro/acronym expansion of the collaborators agencies/companies. In contents/coverpage.tex, line 48m if we change it from \ac to ac* it invokes the acronym package and fixes all of those things like DoD!.

**Comment by nspark** [comment] 2017-07-27 12:45
@swpoole Huh? What does Fortran deprecation and acronym expansion have to do with this issue?

**Comment by swpoole** [comment] 2017-07-27 13:15
Sorry. Conflating several things into one post.
For this topic, it should have just been just that I have fixed the OmniGraffle images.

**Comment by swpoole** [comment] 2017-08-08 03:34
I have created a new version of the image.

**Comment by swpoole** [comment] 2017-08-24 03:34
Here is an updated version of the pdf. If it looks fine to everyone, I will upload the graffle version.
[quiet.pdf](https://github.com/openshmem-org/specification/files/1247656/quiet.pdf)

**Comment by shamisp** [comment] 2017-08-24 04:09
Looks good to me

**Comment by swpoole** [comment] 2017-08-24 10:28
Thanks. Here are both.

[quiet.pdf](https://github.com/openshmem-org/specification/files/1248496/quiet.pdf)

**Comment by swpoole** [comment] 2017-08-24 10:29
Graffle is not supported in the upload. I will send it to the owner of that section.

**Comment by jdinan** [comment] 2017-09-07 16:35
Has the fix for this been incorporated by the relevant section committee?

**Comment by spotluri** [comment] 2017-09-07 16:50
Yes Jim. This is part of the section PR.

**Comment by jdinan** [comment] 2017-09-07 17:25
If the issue is resolved, please close it (but you can leave it in your column on the 1.4 project and it will display as closed).  This will help with reviewing open issues at the RCM.

**Closed** 2017-09-07 18:00 UTC
Labels: Section
